config/routes.rb
SiteStructureAnalyzer::Application.routes.draw do

  resources :pages do
    collection do
      get :problems
      get :nofollow
      get :w3cproblems
    end
    resources :pages_links, :as => :seo do
      collection do
        get :links
        get :backlinks
      end
    end
  end

  root :to => "pages#index"

end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :links, :through => :from_pages_links, :source => "to_page"
  has_many :from_pages_links, :class_name => "PagesLink", :foreign_key => "from_page_id"

  has_many :backlinks, :through => :to_pages_links, :source => "from_page"
  has_many :to_pages_links, :class_name => "PagesLink", :foreign_key => "to_page_id"


  def self.update_links_count
    Page.all.each do |page|
      page.update_attributes(:links_count => page.links.count)
      page.update_attributes(:backlinks_count => page.backlinks.count)
    end

  end

  def w3validate(body)
    if SPIDER_CONFIG["w3c_check_active"]
      @@validator ||= W3CValidators::MarkupValidator.new(:validator_uri => SPIDER_CONFIG['w3c_url'])
      self.w3errors = @@validator.validate_text(body).errors.count
    end
  end

  def validate_url
    URI.join( SPIDER_CONFIG['w3c_url'], "?uri=#{CGI.escape(self.url)}" ).to_s
  end

end

app/models/pages_link.rb
class PagesLink < ActiveRecord::Base
  belongs_to :from_page, :class_name => "Page"
  belongs_to :to_page, :class_name => "Page"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.xml
  def index
    @pages = Page.find_for_table(params)
  end

  def problems
    @pages = Page.where("status_code > '200' or url like '%q=%'").find_for_table(params)
    render :action => :index
  end

  def nofollow
    @pages = Page.joins(:to_pages_links).where("pages.external=1").where("pages_links.no_follow = 0").group("pages.id").find_for_table(params)
    render :action => :index
  end

  def w3cproblems
    @pages = Page.where("w3errors > 0").find_for_table(params)
    render :action => :index
  end

  # GET /pages/1
  # GET /pages/1.xml
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.xml
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.xml
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to(@page, :notice => 'Page was successfully created.') }
        format.xml  { render :xml => @page, :status => :created, :location => @page }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.xml
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to(@page, :notice => 'Page was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.xml
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to(pages_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_links_controller.rb
class PagesLinksController < ApplicationController
  # GET /pages_links
  # GET /pages_links.xml

  # GET /pages_links/1
  # GET /pages_links/1.xml
  def show
    @pages_link = PagesLink.find(params[:id])

  end
  def links
    @page = Page.find(params[:page_id])
    @pages_links = PagesLink.where(:from_page_id => @page.id)
    if request.xhr?
      render :layout => false
    end
  end

  def backlinks
    @page = Page.find(params[:page_id])
    @couples = PagesLink.where(:to_page_id => @page.id)
    @couples = @couples.group_by{|i| i.from_page_id }.sort_by{|i| -i[1].count}
    if request.xhr?
      render :layout => false
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pages_links_helper.rb
module PagesLinksHelper

  def format_page(page)
    url = URI.parse page.url
    url.host = nil
    url.scheme = nil
    link_to truncate(url.to_s, :length => 70), page.url, :target => "_blank"
  end

  def format_link_text(text)
    content_tag :acronym, :title => text do
      truncate text, :length => 40 
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SiteStructureAnalyzer</title>
  <%= stylesheet_link_tag :all ,:tabulatr %>
  <%= stylesheet_link_tag  "/facebox/facebox.css" %>
  <%= javascript_include_tag :defaults, "/facebox/facebox" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id='container'>
  <nav>
  
  <span>SiteStructureAnalyzer</span>
    <span><%= link_to "Seiten", pages_path %></span>
  
  </nav>

<%= yield %>
</div>
</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :status_code %><br />
    <%= f.text_field :status_code %>
  </div>
  <div class="field">
    <%= f.label :aliase %><br />
    <%= f.text_area :aliase %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Alle gecrawlten Seiten</h1>
<ul>
  <li>
    <%= link_to "potenzielle Problemseiten -> StatusCode nicht 200, oder hat ?q= in der URL", "/pages/problems" %>
  </li>
  <li>
    <%= link_to "Externe mit min. 1 Backlink ohne relnofollow", "/pages/nofollow" %>
  </li>
  <li>
    <%= link_to "W3 Fehler", "/pages/w3cproblems" %>
  </li>
  <li>
    <%= link_to "Alle", "/pages" %>
  </li>
</ul>

<%=table_for @pages,     {
  :select_controls => [],
  :submit_label => "Anwenden",
  :info_text => "Zeige %1$d, gesamt %2$d",
} do |t|
  t.column :title do |item|
    if item.title
      link_to truncate(item.title, :length => 50), item
    else
      "-"
    end
  end
  t.column :url do |item|
    if item.url
      link_to truncate(item.url, :length => 60), item.url, :target => "_blank"
    else
      ""
    end
  end
  t.column :status_code, :header => "Status"
  #t.column :size do |item|
  #  (item.size / 1024).to_s + "kb" rescue "-"
  #end
  t.column :links_count, :header => "links #" do |item|
    link_to (item.links_count || "?"), links_page_seo_index_path(item), :rel => :facebox
  end
  t.column :backlinks_count, :header => "Backlink #" do |item|
    link_to (item.backlinks_count || "?"), backlinks_page_seo_index_path(item), :rel => :facebox
  end
  t.column :external, :header => "Extern"
  t.column :w3errors, :header => "Anz. W3 Fehler" do |page|
    if page.w3errors? and page.w3errors > 0
      link_to page.w3errors, page.validate_url, :target => "_blank"
    else
      "0"
    end
  end
end %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<h2>Seite: <%= @page.url %></h2>
<div class='info'>
  <ul>
    <li><%= link_to @page.url,@page.url, :target => "_blank" %>, <%= @page.title %></li>
    <li>Status: <%= @page.status_code %> (200 heißt, alles in Ordnung)</li>
    <li><%= @page.backlinks.count %> <b>Backlinks</b> ingesamt</li>
    <li>davon <%= @page.backlinks.group(:from_page_id).all.count %> <b>Backlinks von einmaligen Seiten</b></li>
    <li><%= @page.links.count %> <b>Links</b> ingesamt</li>
    <li>davon <%= @page.links.group(:to_page_id).all.count %> Links effektiv einmalige Seiten</li>
  </ul>
</div>


<a href='<%= backlinks_page_seo_index_path(@page) %>' class='remote-toggle' id='open-links'>Links auf diese Seite anzeigen (Backlinks)</a>
<div id='open-links-container'></div>


<a href='<%= links_page_seo_index_path(@page) %>' class='remote-toggle'  id='open-backlinks'>Links von dieser Seite anzeigen</a>
<div id='open-backlinks-container'></div>

app/views/pages_links/_form.html.erb
<%= form_for(@pages_link) do |f| %>
  <% if @pages_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pages_link.errors.count, "error") %> prohibited this pages_link from being saved:</h2>

      <ul>
      <% @pages_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_page_id %><br />
    <%= f.text_field :from_page_id %>
  </div>
  <div class="field">
    <%= f.label :to_page_id %><br />
    <%= f.text_field :to_page_id %>
  </div>
  <div class="field">
    <%= f.label :no_follow %><br />
    <%= f.check_box :no_follow %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages_links/backlinks.html.erb
<h2>Links auf diese Seite</h2>

<table class="tabulatr_table">
  <tr>
    <th><acronym title="Titel Attribut des zeigenden Links">A:Title</acronym></th>
    <th><acronym title="Text/Beschreibung des Links">A:InnerText</acronym></th>
    <th>A:nofollow?</th>
    <th colspan="2">A:url</th>
    <th># Backlinks von hier</th>
  </tr>
  <% @couples.each do |page_id,items| 

    item = items.first
    count = items.count
%>
  <tr>
    <td><acronym title="<%=item.title %>">
        <%=truncate item.title, :length => 40 %>
    </acronym></td>
    <td><acronym title="<%=item.title %>"><%=truncate item.inner_text, :length => 40 %></acronym></td>
    <td><%= item.no_follow %></td>
    <td><%= format_page item.from_page %> </td>
    
    <td>
      <%= link_to item.from_page do %>
        <%= image_tag "/images/search_button_16.png" %>
      <% end %>
    </td>
    <td><%=count %></td>
  
  </tr>
<% end %>
</table>

app/views/pages_links/edit.html.erb
<h1>Editing pages_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @pages_link %> |
<%= link_to 'Back', pages_links_path %>

app/views/pages_links/index.html.erb
<h1>Listing pages_links</h1>

<table>
  <tr>
    <th>From page</th>
    <th>To page</th>
    <th>No follow</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages_links.each do |pages_link| %>
  <tr>
    <td><%= pages_link.from_page_id %></td>
    <td><%= pages_link.to_page_id %></td>
    <td><%= pages_link.no_follow %></td>
    <td><%= pages_link.title %></td>
    <td><%= link_to 'Show', pages_link %></td>
    <td><%= link_to 'Edit', edit_pages_link_path(pages_link) %></td>
    <td><%= link_to 'Destroy', pages_link, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pages link', new_pages_link_path %>

app/views/pages_links/links.html.erb
<h2>Links von dieser Seite</h2>

<table class="tabulatr_table">
  <tr>
    <th><acronym title="Titel Attribut des zeigenden Links">A:Title</acronym></th>
    <th><acronym title="Text/Beschreibung des Links">A:InnerText</acronym></th>
    <th>A:nofollow</th>
    <th>A:url</th>
  </tr>
<% @pages_links.each do |item| %>
  <tr>
    <td><%=format_link_text item.title %></td>
    <td><%=format_link_text item.inner_text %></td>
    <td><%= item.no_follow %></td>
    <td><%= format_page item.to_page %> </td>
    <td>
      <%= link_to item.to_page do %>
        <%= image_tag "/images/search_button_16.png" %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/pages_links/new.html.erb
<h1>New pages_link</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_links_path %>

app/views/pages_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From page:</b>
  <%= @pages_link.from_page_id %>
</p>

<p>
  <b>To page:</b>
  <%= @pages_link.to_page_id %>
</p>

<p>
  <b>No follow:</b>
  <%= @pages_link.no_follow %>
</p>

<p>
  <b>Title:</b>
  <%= @pages_link.title %>
</p>


<%= link_to 'Edit', edit_pages_link_path(@pages_link) %> |
<%= link_to 'Back', pages_links_path %>